[package]
name = "badapple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.17.0", features = ["alloc", "exts"] }

[[bin]]
name = "badapple"
test = false
bench = false
